In [1]:
import numpy as np
import pandas as pd

In [2]:
crd=pd.read_csv("Credit.csv")

In [3]:
crd.head()

Credit  RevolvingUtiOfUnsecuredLines  age  NoofTime30_59DaysPastDue  \
0       1                      0.766127   45                         2   
1       0                      0.957151   40                         0   
2       0                      0.658180   38                         1   
3       0                      0.233810   30                         0   
4       0                      0.907239   49                         1   

   DebtRatio  MonthlyIncome  NoOfOpenCreditLinesAndLoans  \
0   0.802982           9120                           13   
1   0.121876           2600                            4   
2   0.085113           3042                            2   
3   0.036050           3300                            5   
4   0.024926          63588                            7   

   NorOfTimes90DaysLate  NoRealEstateLoansOrLines  NoOfTime60_89DaysPastDue  \
0                     0                         6                         0   
1                     0                         0                         0   
2                     1                         0                         0   
3                     0                         0                         0   
4                     0                         1                         0   

   NoOfDependents  
0               2  
1               1  
2               0  
3               0  
4               0

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
# Build a Model for SqFt and Bedrooms
#separate features and outcome

x=crd[['RevolvingUtiOfUnsecuredLines','NoofTime30_59DaysPastDue','MonthlyIncome','NoOfOpenCreditLinesAndLoans','NorOfTimes90DaysLate', 'NoRealEstateLoansOrLines', 'NoOfDependents']]
y=crd['Credit']

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [8]:
#creating estimator object for standardization
from sklearn.preprocessing import StandardScaler
stdSC=StandardScaler()
stdSC.fit(x_train)
x_train_std=stdSC.transform(x_train)
x_test_std=stdSC.transform(x_test)


In [10]:
x_train_std

array([[-0.03257595, -0.10943931, -0.42785467, ..., -0.06073344,
        -0.93808132, -0.72868913],
       [-0.0301591 , -0.10943931,  0.85660921, ..., -0.06073344,
        -0.03955944,  1.03558274],
       [-0.03264654, -0.10943931,  0.2282842 , ..., -0.06073344,
        -0.93808132, -0.72868913],
       ...,
       [-0.03301088, -0.10943931, -0.595408  , ..., -0.06073344,
        -0.93808132, -0.72868913],
       [-0.03288059, -0.10943931,  0.30938001, ..., -0.06073344,
        -0.03955944,  0.15344681],
       [-0.03223034, -0.10943931,  0.62019145, ..., -0.06073344,
        -0.03955944,  0.15344681]])

In [11]:
crdModel=LogisticRegression(max_iter=1000)

In [13]:
crdModel.fit(x_train_std,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
crdModel.coef_

array([[ 0.0306339 ,  0.646055  , -0.37435389, -0.19172019, -0.52024196,
         0.16579487,  0.14067535]])

In [15]:
crdModel.intercept_

array([-2.77368604])

In [17]:
crdModel.predict(x_train_std)

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
crdModel.score(x_train_std,y_train)

0.9367004485794983

In [20]:
print("Train Score: ", crdModel.score(x_train_std,y_train))
print("Test Score: ", crdModel.score(x_test_std,y_test))

Train Score:  0.9367004485794983
Test Score:  0.9322371699053313


In [21]:
predicted_train=crdModel.predict(x_train_std)

In [22]:
predicted_train

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
# generate Confusion Matrix
pd.crosstab(y_train,predicted_train)

col_0      0  1
Credit         
0       5635  4
1        377  3

In [24]:
# Accuracy can be derived from confusion matrix
(5621+9)/x_train.shape[0]

0.9353713241402226

In [25]:
crd.Credit.value_counts()

0    7509
1     517
Name: Credit, dtype: int64

In [26]:
# Precision = Tp/(TP+FP) (If your model needs FP is less, Precision needs to be maximized)
3/(3+4)

0.42857142857142855

In [27]:
# Recall = TP/(TP+FN) (If your model needs FN is less, Recall needs to be maximized)
3/(3+5635)

0.000532103582830791